Develop
Leen-odeh3/Restaurant-Reservation-System pull request #3
Opened 2024-05-19 07:18 UTC by Leen-odeh3

2024-05-19 10:21 UTC, ahmad-m-abbas requested changes

2024-05-19 10:21 UTC, ahmad-m-abbas commented on RestaurantReservation.Db/Abstracts/ICustomerRepository.cs
> +}
```suggestion
namespace RestaurantReservation.Db.Abstracts;
public interface ICustomerRepository : IRepository<Customer>
{
}
```

2024-05-19 10:21 UTC, ahmad-m-abbas commented on RestaurantReservation.Db/Configuration/EmployeeConfiguration.cs
> +            builder.HasOne(e => e.Restaurant)
Format to vertical calls

2024-05-19 10:21 UTC, ahmad-m-abbas commented on RestaurantReservation.Db/Entities/Customer.cs
> +        public ICollection<Reservation>? Reservations { get; set; } = new List<Reservation>();
```suggestion
        public virtual ICollection<Reservation>? Reservations { get; set; }
```

2024-05-19 10:21 UTC, ahmad-m-abbas commented on RestaurantReservation.Db/Entities/Reservation.cs
> +        public int? CustomerId { get; set; }
can a foreign key be null?

2024-05-22 12:14 UTC, ahmad-m-abbas commented on RestaurantReservation.Db/Abstracts/ICustomerRepository.cs
> +    }
?

2024-05-22 12:30 UTC, Leen-odeh3 commented on RestaurantReservation.Db/Abstracts/ICustomerRepository.cs
> +    }
delete it ? Not used anywhere

2024-05-24 07:29 UTC, ahmad-m-abbas approved these changes

2024-05-27 08:50 UTC, ahmad-m-abbas commented
@Leen-odeh3 resolve conflicts

2024-05-29 09:52 UTC, merged